### ISSUE TITLE
[QUESTION] - Is source code for nepsejwtutils.wasm available? 

### ISSUE THREAD

**Issue by sujit-baniya** [ravilmc/nepsetools#1]
Is source code for nepsejwtutils.wasm available?

**Comment by ravilamichhane** [comment]
It is the wasm file that nepalstock.com uses to generate the tokens.
It is available at 

https://www.nepalstock.com/assets/prod/css.wasm

I used wasm2c to convert it to c and used information from the generated c code.

[wasm2c library](https://github.com/WebAssembly/wabt/blob/main/wasm2c/README.md)
